### ISSUE TITLE
Loading segmentation table in merged grid fails

### ISSUE THREAD

**Issue by constantinpape** [mobie/mobie-viewer-fiji#890]
Loading a segmentation table in a merged grid fails now (it used to work a couple releases earlier!). See the error message below.

To reproduce:
- Open the https://github.com/mobie/htm-test project
- Activate `segmentation-cells`

(I also tried this with a couple of other projects that have segmentations in merged grids and get the same error in all of them.)

```
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:657)
	at java.util.ArrayList.get(ArrayList.java:433)
	at org.embl.mobie.viewer.table.saw.TableSawAnnotationTableModel.annotation(TableSawAnnotationTableModel.java:209)
	at org.embl.mobie.viewer.annotation.DefaultAnnotationAdapter.createVariable(DefaultAnnotationAdapter.java:58)
	at org.embl.mobie.viewer.source.AnnotatedLabelSource.getSource(AnnotatedLabelSource.java:61)
	at org.embl.mobie.viewer.image.StitchedImage$RandomAccessibleSupplier.open(StitchedImage.java:694)
	at org.embl.mobie.viewer.image.StitchedImage$StitchedLocationToValueSupplier$RandomAccessibleOpener.run(StitchedImage.java:418)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by constantinpape** [comment]
@tischi: did this maybe stop working when you improved the loading for merged grids? (Which works much smoother now!)

**Comment by tischi** [comment]
Should be fixed in `3.0.2-SNAPSHOT`.

**Comment by tischi** [comment]
But I could not find `segmentation-cells`, only `simple-grid`...

**Comment by constantinpape** [comment]
`segmentation-cells` is available in the default view already, see the only active source in this screenshot.

![image](https://user-images.githubusercontent.com/4263537/199601803-42418ba2-8244-466e-acac-6810fbe5a742.png)

> Should be fixed in `3.0.2-SNAPSHOT`.

Have you uploaded that one already? Because the error is still there for me.

**Comment by constantinpape** [comment]
It's fixed now, thanks!
